### ISSUE TITLE
Warning: exposes your complete ENV by default

### ISSUE THREAD

**Issue by gr8bit** [roest01/docker-coming-soon-generator#1]
Unless you don't supply a config/config.json, this image will put all your ENV variables into that file, posing a high security vulnerability.

@author: the image should only put the variables it knows into that file. And move the config file outside the nginx accessible scope so it cannot be requested.

**Comment by PrinzJuliano** [comment]
Hi, could you further explain the issue. When running docker build and docker run the only variables placed in the config file are: 
```json
{
    "BASE_DIR": "/usr/share/nginx/html",
    "HOME": "/root",
    "HOSTNAME": "81c96d091dd1",
    "NGINX_VERSION": "1.23.2",
    "NJS_VERSION": "0.7.7",
    "OLDPWD": "/usr/share/nginx/html",
    "PATH": "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
    "PKG_RELEASE": "1~bullseye",
    "PWD": "/usr/share/nginx/html",
    "SHLVL": "1",
    "TEMPLATE": "blank",
    "config": true
}
```

**Comment by roest01** [comment]
this was fixed with https://github.com/roest01/docker-coming-soon-generator/pull/2/commits/7b270f6c2febba4438a03eeb4bf0a1b31222fe5c
